server:
  address: localhost
  port: 10080

logging:
  level:
    root: INFO
    pers.zxt.cloud.gateway: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: gateway
  profiles:
    active: dev
    # 引入路由配置(application-gateway-route.yml) -------------- KEY
    include: gateway-route

  cloud:
    gateway:
      # 开启网关（默认值）
      enabled: true

# 可选：暴露 actuator 端点（用于 Sentinel 控制台）
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
#   endpoint:
#     health:
#       show-details: always

---
# ---------- 开发环境 ----------
spring:
  config:
    activate:
      on-profile: dev
  # SpringCloud-Nacos 配置
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
      # 服务注册/发现
      discovery:
        service: ${spring.application.name}
        ip: localhost  # 服务注册的IP，默认为宿主机的IP
        namespace: dev
        # 由于默认下服务注册和发现都是在同组中进行的，不能跨group进行服务发现，所以这里的分组不能像配置中心那样每个服务一组
        #group: user

---
# ---------- 生产环境 ----------
spring:
  config:
    activate:
      on-profile: prod
  # SpringCloud-Nacos 配置
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
      # 服务注册/发现
      discovery:
        service: ${spring.application.name}
        ip: localhost  # 服务注册的IP，默认为宿主机的IP
        namespace: prod
        # 由于默认下服务注册和发现都是在同组中进行的，不能跨group进行服务发现，所以这里的分组不能像配置中心那样每个服务一组
        #group: user
